### ISSUE TITLE
Better Capture point/Flag indicator

### ISSUE THREAD

**Issue by Aaronek10** [Emana202/Lambda-Players-Team-System#3]
To make Team System a bit more better looking especially in KOTH/CP or CTF

I thought about adding special icon above capture points, which will render on HUD and follow location offscreen, also Outline will show status of capturing/neutralizing point.
First letter of point name or by setting in tool will be inside this icon or full name under/above icon.

Icons:
Circle
Square
Triangle
or
Custom Material (similar to adding a new texts, voices etc)

Similar for CTF, where it will show spot where flag is and also will follow the carrier.

This idea is a slight improvement of Team System to make it more better

**Comment by Emana202** [comment]
Something like this?
![Screenshot_75](https://user-images.githubusercontent.com/87763830/219425071-d5533711-7075-4eb4-873a-c6debea4ee3e.png)
![Screenshot_74](https://user-images.githubusercontent.com/87763830/219425087-ad9d1a35-3bcd-46d1-8c88-fdfedb953158.png)

**Comment by Aaronek10** [comment]
Yup, similar for Capture Points where border of circle will show status of capturing/neutralizing

Also both should work offscreen for better locating

I think you can use this as inspiration: https://github.com/Bambofy/ConquestSystem
file `cl_main.lua` have some code for making offscreen indicator as well setting max distance for them, because i find indicators running around my monitor is more annoying since they are very inaccurate and sometimes "flashes" from one corner to other

**Comment by Emana202** [comment]
https://user-images.githubusercontent.com/87763830/219455024-4b1a0f88-b48f-4fd7-9088-7c807a40f0fd.mp4

**Comment by Aaronek10** [comment]
Looks good.

This is my little suggestion to make it a bit more accurate bcuz this flinching is quite... bad looking:
Invisible circle which around indicator will move, making it much smoother and better looking (propably hard to do)
![image](https://user-images.githubusercontent.com/37957871/219456554-000ad797-e6db-405e-a890-b52a676c7975.png)
(Garbage edit, sorry xd)


Additionally:
Settings
1.  Enable/Disable icons
2. Max distance before they start fading or visible all the time
